name: deploy


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: pull repository on server
        run: ./home/xnoahg/actions-runner/deploy.sh
    

